# Generated by Django 5.2.4 on 2025-07-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_remove_usergroup_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaincategory',
            name='cat_ordering',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
